version: '3.1'
services:
  web:
    container_name: ${ODOO_CONTAINER_NAME}
    image: odoo-debug:${ODOO_VERSION}
    depends_on:
      - postgres
    ports:
      - '${ODOO_PORT_CUSTOM}:${ODOO_PORT_DEFAULT}'
      - '${DEBUGPY_PORT}:${DEBUGPY_PORT}'
    volumes:
      - ./conf:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - ${CUSTOM_ADDONS}:/var/lib/odoo/custom_addons
    entrypoint: ${ENTRYPOINT}
  postgres:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:${PG_VERSION}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PG_PORT}:5432
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
